project_id = "ddtvbwugxvkszvweqkfa"

[functions.request-password-reset]
verify_jwt = false

[functions.confirm-password-reset]
verify_jwt = false

[functions.ipaymoney-callback]
verify_jwt = false

[functions.ipay-webhook]
verify_jwt = false
