// Confirms a password reset using a 6-digit OTP previously generated by
// request-password-reset. Validates code + sets new password via admin API.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const normalize = (raw: string) => (raw || "").replace(/\D/g, "");

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const { phone, code, newPassword } = await req.json();
    const digits = normalize(phone);
    const cleanCode = String(code || "").trim();

    if (digits.length < 8) return json({ success: false, message: "Numéro invalide" }, 400);
    if (!/^\d{6}$/.test(cleanCode))
      return json({ success: false, message: "Code à 6 chiffres requis" }, 400);
    if (!newPassword || String(newPassword).length < 8)
      return json({ success: false, message: "Mot de passe trop court (min 8)" }, 400);

    const admin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // Lookup latest active code for this phone
    const { data: rec } = await admin
      .from("password_reset_codes")
      .select("*")
      .eq("phone", digits)
      .eq("used", false)
      .gte("expires_at", new Date().toISOString())
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    if (!rec) return json({ success: false, message: "Code invalide ou expiré" }, 400);
    if ((rec.attempts ?? 0) >= 5) {
      await admin.from("password_reset_codes").update({ used: true }).eq("id", rec.id);
      return json({ success: false, message: "Trop de tentatives. Demandez un nouveau code." }, 429);
    }

    if (rec.code !== cleanCode) {
      await admin
        .from("password_reset_codes")
        .update({ attempts: (rec.attempts ?? 0) + 1 })
        .eq("id", rec.id);
      return json({ success: false, message: "Code incorrect" }, 400);
    }

    // Resolve user id
    let userId: string | null = null;
    const { data: profile } = await admin
      .from("profiles")
      .select("user_id")
      .eq("phone", digits)
      .maybeSingle();
    if (profile?.user_id) userId = profile.user_id;

    if (!userId) {
      const internalEmail = `${digits}@phone.washgo.local`;
      const { data: list } = await admin.auth.admin.listUsers({ page: 1, perPage: 1000 });
      userId = list?.users?.find((u) => u.email === internalEmail)?.id ?? null;
    }

    if (!userId) return json({ success: false, message: "Compte introuvable" }, 404);

    const { error: updErr } = await admin.auth.admin.updateUserById(userId, {
      password: String(newPassword),
    });
    if (updErr) {
      const msg = updErr.message?.toLowerCase() ?? "";
      if (msg.includes("password")) {
        return json(
          { success: false, message: "Mot de passe trop faible ou compromis. Choisissez-en un autre." },
          400
        );
      }
      return json({ success: false, message: "Erreur : " + updErr.message }, 500);
    }

    await admin.from("password_reset_codes").update({ used: true }).eq("id", rec.id);

    return json({ success: true, message: "Mot de passe réinitialisé" });
  } catch (e) {
    return json({ success: false, message: String(e) }, 500);
  }
});
